# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ControlComac
                                 A QGIS plugin
 Un plugin qui contrôle les études COMAC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-31
        copyright            : (C) 2020 by Simon Ducournau
        email                : simon.ducournau@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ControlComac class from file ControlComac.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .control_comac import ControlComac
    return ControlComac(iface)
